version: '3'

services:
  client:
    image: kainisoft/client
    ports:
      - "4200:4200"
    networks:
      - webgateway
    restart: always

  server:
    image: kainisoft/server
    ports:
      - "4000:4000"
    networks:
      - webgateway
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  webgateway:
    name: webgateway
    driver: bridge
