entryPoints:
  web:
    address: ':80'
  websecure:
    address: ':443'

providers:
  docker:
    exposedByDefault: false
    network: webgateway
  file:
    directory: /etc/traefik/conf
    watch: true

certificatesResolvers:
  myresolver:
    acme:
      tlschallenge: true
      email: kainisoft@gmail.com
      storage: /letsencrypt/acme.json
      # caserver: https://acme-staging-v02.api.letsencrypt.org/directory
      httpchallenge:
        entryPoint: web

api:
  insecure: true
  debug: true

log:
  level: DEBUG
  filePath: /var/log/traefik/traefik.log
  maxBackups: 7
  maxAge: 7
  compress: true
